### ISSUE TITLE
JSeg trained model for demo.py

### ISSUE THREAD

**Issue by ramsever** [Jittor/JSeg#1]
Is it possible for you to provide a trained model for the demo in JSeg:
ckp_file = 'work_dirs/fcn_r50-d8_512x1024_cityscapes_80k/checkpoints/ckpt_80000.pkl'
Thank you very much for your help!

**Comment by uyzhang** [comment]
You can use the trained model of [segnext](https://github.com/Jittor/JSeg/tree/main/project/segnext) in the demo.

**Comment by ramsever** [comment]
Thanks
