### ISSUE TITLE
Any trained weights offered?

### ISSUE THREAD

**Issue by BobM-DS** [Jittor/JSeg#7]
Can you provide a weight file that has been trained for inferencing a single image?
Thank you a lot.

**Comment by BobM-DS** [comment]
this link: https://github.com/Jittor/JSeg/tree/main/project/clip_rc

**Comment by uyzhang** [comment]
Hi, this repository supports inference for this method, but if you need training, you can use this repo: https://github.com/uyzhang/CLIP-RC.
